-- Script that specifies various users to be created
-- adminal^1
CREATE USER ADMIN_ALUMNI@localhost IDENTIFIED BY PASSWORD '*DC2C0530093137DEA94DE703B8556F2A69BA6769';

GRANT ALL PRIVILEGES ON *.* TO ADMIN_ALUMNI@localhost WITH GRANT OPTION 
MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

-- soal^2
CREATE USER SO_ALUMNI@localhost IDENTIFIED BY PASSWORD '*6A830C6FEB6A711DB6AB4B0D0679A7B08C77AD4C';

GRANT 	SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, PROCESS, FILE, REFERENCES, INDEX, ALTER, 
		SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, EVENT, TRIGGER, 
		SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON *.* TO 'SO_ALUMNI'@'localhost' WITH GRANT OPTION 
		MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
		
--olal^3
CREATE USER OL_ALUMNI@localhost IDENTIFIED BY PASSWORD '*E6D3D2B9C777E77DFCF505374FDA8823B4967D46';

GRANT 	SELECT, INSERT, UPDATE, DELETE, FILE, EXECUTE ON *.* TO OL_ALUMNI@localhost;  